#!/bin/bash
#
# cafworker    Startup script for the Common Analysis Framework TaskWorker
#
# chkconfig:   2345 95 05
# description: Common Analysis Framework TaskWorker daemon
# processname: MasterWorker.py
# pidfile: /var/run/cafworker.pid

SU_USER="mcinquil"
SU_WRAP="sudo -H -u $SU_USER bashs -l -c"

DAEMON_PATH="/data/TaskManager/COM/CAFTaskWorker/"

#DAEMON="$DAEMON_PATH/src/python/TaskWorker/MasterWorker.py"
#DAEMONOPTS="--config $DAEMON_PATH/etc/TaskWorkerConfig.py --db-config /data/TaskManager/config_db.py"

NAME="cafworker"
DESC="Common Analysis Framework TaskWorker"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
start)
    printf "%-50s" "Starting $NAME..."
    cd $DAEMON_PATH
    PID=`$SU_WRAP 'source /data/TaskManager/comenv.sh; /data/TaskManager/COM/CAFTaskWorker/src/python/TaskWorker/MasterWorker.py --config /data/TaskManager/devel/CAFTaskWorker/etc/TaskWorkerConfig.py --db-config /data/TaskManager/config_db.py > /tmp/log.log.log 2>&1 & echo "$!" '`
    echo "Saving PID" $PID " to " $PIDFILE
        if [ -z $PID ]; then
            printf "%s\n" "Fail"
        else
            echo $PID > $PIDFILE
            printf "%s\n" "Ok"
        fi
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME"
            PID=`cat $PIDFILE`
            cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
            kill -HUP $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
    $0 stop
    $0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
